FROM node:16-alpine
RUN yarn global add @nestjs/cli
WORKDIR /api
COPY package.json yarn.lock ./
RUN yarn install --prod --frozen-lockfile
COPY . .

RUN yarn run prisma generate

EXPOSE 3000
RUN chmod +x ./start.sh
CMD ["./start.sh"]