version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - type: bind
        source: .
        target: /api
    environment:
      # postgresql URL: postgresql://<user>:<password>@<host>:<port>/<database>?schema=<schema>
      - DATABASE_URL=postgresql://user:password@db/db?schema=public
    command:
      - /bin/sh
      - -c
      - |
        yarn prisma:generate &
        yarn prisma:migrate &
        yarn prisma:studio &
        yarn start

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: