version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ttv-postgres/postgres?schema=public

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: