FROM node:16-alpine
RUN yarn global add @nestjs/cli
WORKDIR /api
COPY package.json yarn.lock ./
RUN yarn install --prod --frozen-lockfile
COPY . .

ARG _DATABASE_URL
ENV DATABASE_URL=${_DATABASE_URL}
RUN echo ${DATABASE_URL}

RUN yarn run prisma generate
RUN yarn run prisma migrate deploy

EXPOSE 3000
CMD ["yarn", "run", "start"]